@WebHook.Api_HostAddress = http://localhost:5214

### Create Order
Post {{WebHook.Api_HostAddress}}/orders
Content-Type: application/json
{
  "customerName": "string",
  "amount": 123
}

### Create Subscriptions
POST {{WebHook.Api_HostAddress}}/webhooks/subscriptions
Content-Type: application/json

{
  "eventType": "order.created",
  "webhookUrl": "https://webhook.site/4be62c82-f319-4230-aaa1-746035ceed87"
}

