using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

namespace SampleGenerator;

[Generator]
public class ClassNameGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (c,_)=> c is ClassDeclarationSyntax,
            transform: (n, _) => (ClassDeclarationSyntax) n.Node).Where(m => m is not null);
        var compilation = context.CompilationProvider.Combine(provider.Collect());
        context.RegisterSourceOutput(compilation, (spc, source) => Execute(spc, source.Left, source.Right));
    }

    private void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax> typeList)
    {
        var code = """
                    //<auto-generated/>
                    namespace SampleGenerator
                    {
                        public static class EndpointsExtension
                        {
                            public static string MapAllEndpoints(this string endpoints)
                            {
                                return endpoints;
                            }
                        }
                    }
                    """;
        context.AddSource("EndpointsExtensions.g.cs", code);
    }
}


